[package]
name = "template-game-devy"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy = "0.14.2"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
incremental = true